SELECT * FROM CUSTOMER

--Q1. What  is the total revenue generated by male vs female customers?

select gender, SUM(purchase_amount_usd) as revenue
from customer
Group by gender

--Q2. Which Customers used a discount but still spent more than the average purchase amount?

select customer_id, purchase_amount_usd
from customer
where discount_applied = 'Yes' and purchase_amount_usd >= (select AVG(purchase_amount_usd) from customer)

--Q3. Which are the top 5 products with highest average rating?

select item_purchased, ROUND(AVG(review_rating::NUMERIC),2) AS "Average rating"
from customer
group by item_purchased
order by avg(review_rating) desc 
limit 5;

--q4. Compare the average purchase amounts between standard and express shipping

SELECT shipping_type,
AVG(purchase_amount_usd)
from customer 
where shipping_type in ('Standard','Express')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue

select subscription_status,
COUNT(customer_id) as total_customer,
SUM(purchase_amount_usd) as total_revenue,
AVG(purchase_amount_usd) as average_spent
from customer
group by subscription_status
order by total_revenue, average_spent

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
round(100*SUM(CASE WHEN discount_applied='YES' THEN 1 ELSE 0 END)/Count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--Q7. Segment customers into New, Returning and loyal based ontheir total number of previous purchases, and show the count of each segment

with customer_type as (
select customer_id, previous_purchases,
CASE 
WHEN previous_purchases = 1 THEN 'New'
WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
ELSE 'Loyal' END AS customer_segment
from customer
)

select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment

--Q8. WHAT ARE THE TOP 3 MOST PURCHASED PRODUCTS WITHIN EACH CATEGORY?

with item_counts as (
select category, item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank
from customer
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

--Q9. Are customers who are repeat buyers (morew than 5 previous purchases) also likely to subscribe?

select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases >5
group by subscription_status

--Q10. What is the revenue contribution of each age group?
select age_group,
SUM(purchase_amount_usd) as total_revenue
from customer
group by age_group
order by total_revenue desc